### ISSUE TITLE
Sberbank2Excel x64 4.0.0 fails to run on Windows 7 SP1

### ISSUE THREAD

**Issue by A-Kazak** [Ev2geny/Sberbank2Excel#19]
Greetings!

  How do I attack the following issue appearing on Windows 7 SP1

> Error loading Python DLL 'D:\sberbankPDF2ExcelGUI.v.4.0.0\sberbankPDF2ExcelGUI\python39.dll'.
> No error messages generated.
> FormatMessageW: The parameter is incorrect.
> LoadLibrary: PyInstaller: FormatMessageW failed.

![2022-03-10_10h58_26](https://user-images.githubusercontent.com/97515759/157615181-71b87969-0dfe-49dd-9ec6-7efddb24db35.png)

  https://forums.sabnzbd.org/viewtopic.php?t=25287 says that "Windows 7 is no longer supported by Python 3.9."

  Can you share a workaround for Windows 7, please?

Thank you.

**Comment by Ev2geny** [comment]
Unfortunately there is no workaround for Windows 7
The minumal requirement is Windows 8.1. I will update the documentation to make it clear
Yes, it is related to the fact that Windows 7 is no longer supported by Python 3.9

**Comment by A-Kazak** [comment]
> Unfortunately there is no workaround for Windows 7

Is this a complicated to make a version for Python 3.8.x supporting W7?

**Comment by Ev2geny** [comment]
> Is this a complicated to make a version for Python 3.8.x supporting W7?
This probably not very difficult, but this is not something I would like to invest my time in. 
Reasons:
* I would have to limit the code to the Python 3.8 functionality. Since one of my goals is to learn Python, I do not feel like doing this. For the current code i am not 100% sure whether it will run in Python 3.8
* I do not have access to Windows 7, hence testing will become difficult

**Comment by Ev2geny** [comment]
As Microsoft and Python does not support Windows 7, this will not be implemented
